### ISSUE TITLE
Error in py_call_impl()

### ISSUE THREAD

**Issue by parvathisudha** [AlexandrovLab/SigProfilerSimulatorR#1]
Hi,

When I run SigProfilerSimulatorR, I am getting a python value error with no output folder.

Command used:
SigProfilerSimulatorR("MM", "/N/project/WGS/Signature_analysis/SigProfilerMatrixGeneratorR/", "GRCh38", contexts=list(c("96")), exome=NULL, simulations=100, updating=FALSE, bed_file=NULL, overlap=FALSE,chrom_based=FALSE, seed_file=NULL, noisePoisson=FALSE, noiseAWGN=0, cushion=100, region=NULL)

======================================
        SigProfilerSimulator        
======================================

Checking for all reference files and relevant matrices...

Files successfully read and mutations collected. Mutation assignment starting now.
Mutations have been distributed. Starting simulation now...
         Chromosome 21 done
         Chromosome 22 done
         Chromosome 19 done
         Chromosome 20 done
         Chromosome 18 done
         Chromosome 17 done
         Chromosome 16 done
         Chromosome 15 done
         Chromosome 14 done
         Chromosome 13 done
         Chromosome 12 done
         Chromosome 11 done
         Chromosome 10 done
         Chromosome 9 done
         Chromosome 8 done
         Chromosome X done
         Chromosome 7 done
         Chromosome 6 done
         Chromosome 5 done
         Chromosome 4 done
         Chromosome 3 done
         Chromosome 2 done
         Chromosome 1 done
Simulation completed
Job took  226.99054527282715  seconds
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  ValueError: I/O operation on closed file.

Can you please help me to solve this issue?

Thanks
Parvathi.

**Comment by mdbarnesUCSD** [comment]
Please update to the most recent version of the SigProfilerAssignment and reopen this if you encounter this issue.
